### ISSUE TITLE
US: Set Up Development Environment

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#1]
As a **developer** I can  **set up a local development environment ** so that I can **start working on the project.**

## Tasks:

- [x] Install Python and Django on the local machine
- [x] Create a new Django project for La-hotel
- [x] Set up a virtual environment
- [x] Install necessary dependencies
