### ISSUE TITLE
US: Contact/Adress details

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#15]
As a **Site owner** I want to **show our contact and adress details** so that **guests/potential guests can contact us or visit us for queries or make a reservation.**

## Acceptance Criteria:

- When a guest/potential guest visit out website they should easily see our contact and adress details.

## Tasks:

- [ ] Add contact us page
- [ ] Create link in navigation bar
- [x] Add contact details to the footer
