### ISSUE TITLE
US: UX/UI

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#18]
As a **Site Owner** I want  **the website to be a good user experience** so that **site users enjoy their visit and wants to return**

## Acceptance Criteria:

- It is easy and intuitive to navigate the webpage
- Visual feedback is given to user at all times when navigating the webpage
- When guest make changes to their account or reservation, they see confirmation that their action has succeded or failed

## Tasks:

- [x] Add SUCCESS and ERROR messages based on user CRUD actions
- [x] Make sure design follow standard design conventions
- [x] Add visual interactive effects
- [x] Test functionality
