### ISSUE TITLE
US: Create About Page

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#19]
As a **Site Owner** I want to **have an about page** so that **guest/potential guests can learn about our hotel.**

As a **Site User** I can **visit the hotels about page** so that **I can learn more about the story of the hotel.**

## Acceptance Criteria:

- Given that user wants to learn more about us when visiting our webpage, they are able to go to our about page via the navigation bar.

## Tasks:

- [ ] Create about app
- [x] Create link to about page from the navbar
- [x] Design about page according to wireframe
- [x] Test the functionality in dev environment and deployed version

**Comment by EVondrus** [comment]
create a template in home app to be able to use the details from the hotel model in a easier way.
Concider closed
