### ISSUE TITLE
US: Images on Home page

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#21]
As a **Site Owner** I want to **display images of the hotel and room categories** in a stylish manner** so that **site users/potential guests will get exited when they visit the website**

As a **Site User** I can **view images of the hotell and rooms** so that **I know what I can expect**

## Acceptance Criteria:

- Given that a user visits the website  they are displayed with images of the hotel and room categories

## Tasks:

- [x] Add images of the hotel on the landing page
- [x] Add images of the room categories on the landing page
- [x] Ensure the ability to upload and manage images through the Django admin interface
- [ ] Use images from the database
- [x] Or link images from cloudinairy
- [x] Test functionality in dev environment and deployed version
