### ISSUE TITLE
US:  Room Category Image Carousell

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#22]
As a **Site Owner** I want to **be able to display room images in a carousell - when clicked it will redirect to the room category detail page for the user to read further about the room category and book a room**

As a **Site User** I can **quickly view room categories** so that **I can select accommodations that meet my preferences**

## Acceptance Criteria:

- When a room category image in the carousel is clicked then the site user gets redirected to detail page

## Tasks:

- [x] Display room category images in a carousel
- [ ] Redirect to the selected room category detail page
- [x] Test the functionality in dev environment and deployed version
