### ISSUE TITLE
US: Hotel Image Change Transition

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#23]
As a **Site Owner** I want **hotel images on home page to change** so that **the site user see different images of the hotel**

As a **Site User** I can **view different images** so that **I get an overview of the hotel**

## Acceptance Criteria:

- The home page should display different images in a smooth continuous transition

## Tasks:

- [ ] Add functionality to display different images.
- [ ] Ensure the images transitions smoothly between images.
- [ ] Test functionality in dev environ and deoployed version
