### ISSUE TITLE
US: Create room category page

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#24]
As a **Site User** I can **view room categories of the hotel and check the avaliability of my desired dates** so that  I can **get a clear idea of what type of rooms and price range the hotel offers and which room are avaliable for my stay**

## Acceptance Criteria:

- Show all room categories with image, small description, capacity and price
- Check avaliability 

## Tasks:

- [x] Create a room category page and link in navbar
- [x] Implement the grid/list of room categories according to wireframe
- [ ] Add a check-in and check-out form for availability check
- [x] Ensure each room category card links to the corresponding room detail page
- [x] Test functionality on dev environment and deployed version
