### ISSUE TITLE
US: Online room reservation

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#26]
As a **Site user** I can  **book a room online** so that **the reservation will be easier and faster than over phone or email**

## Acceptance Criteria:

- Given that the user is logged onto the webpage when clicking on the "Book room" button, they are able to make a reservation
- Given that user is not logged in when clicking on the "Book room" button then they are prompted to first log in or register an account

## Tasks:
- [x] Create a revervation app
- [x] Create a form for users to input booking details
- [x] Check if the user is logged in when they click the "Book Room" button. Create conditional view based on if user.is_authenticated
- [x] If logged in, direct them to the reservation form, If not logged in, prompt them to log in or register first
- [x] Ensure that reservation details are saved in the database and linked to the user
- [x] Test functionality in dev environment and deployed version
