### ISSUE TITLE
US: Edit/Update Reservation

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#27]
As a **Site User** I can **manage my bookings** so that I can **easily view, update, and cancel my reservations.**
As a **Site User** I can **edit my current reservations** so that I can **have flexibility incase my schedule changes**

## Acceptance Criteria:

- Given that I am logged into the website, I can view my reservations on my profile page.
- Given that I am viewing a booking, I can update its details

## Tasks:

- [x] Implement functionality to view details of each booking
- [x] Add edit button next to the reservation
- [x] Ensure that when users navigate to the update booking page, the booking form is pre-populated with the current information
- [x] Display success or error message upon submitting
- [x] Test functionality in dev environment and deployed version
