### ISSUE TITLE
US: Update/Edit Room Details

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#32]
As a **Site Owner**, I can **edit room details** so that **I can update the information to ensure it is accurate and current.**

## Acceptance Criteria:

- Given that I am logged into the Django admin panel, I can navigate to the room details section
- Given that I have edited the room details, the changes are saved to the database and reflected on the website.

## Tasks:

- [x] Add conditional logic so that only the site owner has permissions to edit room details.
- [x] Ensure that editing room details updates the database and the website.
- [x]  Test the functionality in dev environment and the deployed version
