### ISSUE TITLE
US: Create receptionist dashboard

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#36]
As a **Staff user** I can **access a dedicated staff dashboard** so that **I have a centralized platform to manage hotel guests and reservations efficiently.**

## Acceptance Criteria:

- Upon logging into the system as a staff member, I can navigate to the staff dashboard.
- The staff dashboard provides access to various features and functionalities relevant to hotel operations.

## Tasks:

- [ ] Create reception app
- [ ] Design according to wireframes
- [ ] Create model according to ERD
- [ ] Implement authentication and authorization mechanisms to restrict access to the dashboard.
- [ ] Test functionality in dev enviroment and deployed version
