### ISSUE TITLE
US: Guest Check in - staff

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#40]
As a **Staff User** I can **check in a guest** so that I can **register their arrival and provide access to the room.**

## Acceptance Criteria:

- I have access to a form or interface where I can initiate the check-in process for a specific booking.
- Upon checking in the guest, the room status is updated to indicate that they have arrived.

## Tasks:

- [ ] Design the interface for initiating the check-in process.
- [ ] Implement logic to update the room status to "checked-in" in the database.
- [ ] Test functionality in dev renviroment and deployed version
