### ISSUE TITLE
US: Guest check out

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#41]
As a **Staff User**  I can **check out a guest** so that **I can finalize their stay and have the room prepared for the next guest.**

## Acceptance Criteria:

- Upon checking out the guest, the room status is updated to indicate that the guest have departed.
- If the check-out process is successful, I receive a confirmation message.

## Tasks:

- [ ] Add a button initiating the check-out
- [ ]  Implement logic to update the room status to "checked-out" in the database.
- [ ] Test functionality in dev environment and deployed version
