### ISSUE TITLE
US: Edit/Update Account Information

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#6]
As a **Site User** I can **Edit/Update Account Information** so that I can **I can keep my profile and details up-to-date.**

## Acceptance Criteria:

- Users can edit/update their account and detail information
- Changes are saved and reflected in the user's profile
- Users receive a confirmation message upon successful updates

## Tasks:

- [ ] Utilize Django Allauth's account update feature
- [x] Ensure account information is securely updated
- [x] Changes are displayed to the user and in the admin panel.
- [x] #7

**Comment by EVondrus** [comment]
Instead of using Django allauth account update feature.
I Created a ProfileForm and an EditProfile view( - UpdateView) for the user to be able to update their profile.
The form is prefilled with the information from the signup form and editable in a modal. The new details are saved to the database and displayed to the user.
