### ISSUE TITLE
US: Reset Password

### ISSUE THREAD

**Issue by EVondrus** [EVondrus/la-hotel#7]
As a **Site User** I can **reset password** so that I can **Easily recover my account access if I forget my password**

## Acceptance Criteria:

- Users can request a password reset on the login page.
- Users receive an email with a link to reset their password.
- Users can set a new password using the link provided in the email.

## Tasks:

- [x] Configure the project to use an email backend that supports sending emails
- [x] Use Django's EmailMessage class provided by django-allauth to send an email to the user with a unique password reset link. Utilize django-allauth's built-in mechanisms for generating unique tokens for password reset links.
- [x] Implement a view that handles the password reset process
- [x] On submission, hash the new password and update the user's record in the database.
